<?php
	if(isset($this->post['Titulo']))
	{
		$this->cantidad=$_POST['Titulo'];
	}
	$this->includes=
	[
		'//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js',
		'http://cdn.wysibb.com/js/jquery.wysibb.min.js',
		'http://cdn.wysibb.com/css/default/wbbtheme.css',
		'../js/wysibbInc.js'
	];
	$this->labels=
	[
		[
			'input_text.php',
			'Titulo'
		],
		[
			'editor.php',
			'Descripcion'
		],
		[
			'selector_imagen.php',
			'Imagen'
		],
		[
			'selector_si_no.php',
			'Visible'
		]
	];

	$this->ancla='#nov';
	//$action='../index.php';
	$for='nNov';
?>