<?php
	if(isset($_POST['Titulo']))
	{
		$cantidad=$_POST['Titulo'];
	}
	$includes=
	[
		'//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js',
		'http://cdn.wysibb.com/js/jquery.wysibb.min.js',
		'http://cdn.wysibb.com/css/default/wbbtheme.css',
		'../js/wysibbInc.js'
	];
	$ancla='#nov';
	$action='../index.php';
	$for='nNov';
	$labels=
	[
		[
			'selector_lenguaje.php',
			'Lenguaje'
		],
		[
			'input_text.php',
			'Titulo'
		],
		[
			'editor.php',
			'Descripcion'
		],
		[
			'selector_imagen.php',
			'Imagen'
		],
		[
			'selector_si_no.php',
			'Visible'
		]
	];
?>